version: '3'
services:
  web:
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    container_name: kaikatsu
    environment:
      - MIX_ENV=dev
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
    ports:
      - "4033:4033"
    volumes:
      - .:/kaikatsu
    links:
      - db
  db:
    container_name: kaikatsu-db
    image: postgres:9.5
    environment:
      - POSTGRES_DB=kaikatsu_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
