version: '3'
services:
  web:
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    container_name: kakatsu
    environment:
      - MIX_ENV=dev
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=postgres
    ports:
      - "4033:4033"
    volumes:
      - .:/kakatsu
    links:
      - db
  db:
    container_name: kakatsu-db
    image: postgres:9.5
    environment:
      - POSTGRES_DB=kakatsu_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432
